### ISSUE TITLE
dev guide uses 0x800_0000, should use 0x80_0000

### ISSUE THREAD

**Issue by reticulatedpines** [reticulatedpines/magiclantern_simplified#138]
I probably got this address wrong from memory.  Confirm ML usage of 0x80_0000 and correct usage in https://github.com/reticulatedpines/magiclantern_simplified/blob/dev/developer_guide/03_00_magiclantern.md

Check for bad uses elsewhere.

**Comment by lclevy** [comment]
What about adding a references section, including previous work about dev?

**Comment by reticulatedpines** [comment]
Fixed by https://github.com/reticulatedpines/magiclantern_simplified/commit/7a1ba1401e1a16f489eb14cf072cf254db94610d
