### ISSUE TITLE
(Not an issue) I have an EOS 100D, how can I help?

### ISSUE THREAD

**Issue by UnforeseenOcean** [reticulatedpines/magiclantern_simplified#150]
I really like the new features and I want to help the development of Magic Lantern, but my camera seems to be in "ports in progress" section with the latest build date of 2018. **Is there anything I can do to help as a user?** I may be able to help testing beta builds and more if needed on a real hardware, if given (brief or not) instruction. (e.g. "Install this version and try to test the mirror lock function, then document what it does in such-and-such place with attached log files")

**Comment by reticulatedpines** [comment]
Hi.  Nobody is working on 100D port at this time.  There is nothing you can do to help as a user.

**Comment by reticulatedpines** [comment]
Closing because "not an issue", consider joining the discord, which is a better place for general questions.

**Comment by UnforeseenOcean** [comment]
Bummer. I've reached the limit for the free user, I will try to find a way to clean up the server list so I can join.
